apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minio-demo

resources:
  - namespace.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml

# Optional: uncomment to include the test job
# - test-job.yaml
